using Xunit;

public sealed class RepositoryConventionsTests
{
	private const int MaximumPhysicalLines = 899;
	private static readonly HashSet<string> ExcludedDirectories = new(StringComparer.OrdinalIgnoreCase)
	{
		".git", "bin", "obj"
	};
	private static readonly string[] GeneratedSuffixes =
	{
		".g.cs", ".generated.cs", ".designer.cs", ".AssemblyInfo.cs"
	};

	[Fact]
	public void HandWrittenCSharpFilesStayBelow900Lines()
	{
		Assert.False(ExceedsLimit(MaximumPhysicalLines));
		Assert.True(ExceedsLimit(MaximumPhysicalLines + 1));
		Assert.True(HasGeneratedSuffix("Generated.g.cs"));
		Assert.True(IsExcludedDirectory("obj"));

		var root = FindRepositoryRoot();
		var violations = EnumerateSourceFiles(root)
			.Where(path => !IsGeneratedSource(path))
			.Select(path => new { Path = path, Lines = File.ReadLines(path).Count() })
			.Where(file => ExceedsLimit(file.Lines))
			.OrderBy(file => file.Path, StringComparer.Ordinal)
			.ToArray();

		if (violations.Length > 0)
			Assert.Fail("Hand-written C# files must contain at most 899 physical lines:" + Environment.NewLine +
				string.Join(Environment.NewLine, violations.Select(file =>
					$"  {Path.GetRelativePath(root, file.Path).Replace('\\', '/')}: {file.Lines} lines")));
	}

	private static string FindRepositoryRoot()
	{
		for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent)
			if (File.Exists(Path.Combine(directory.FullName, "shell_lang.slnx")))
				return directory.FullName;
		throw new InvalidOperationException("Could not locate the ShellLang repository root.");
	}

	private static IEnumerable<string> EnumerateSourceFiles(string directory)
	{
		foreach (var file in Directory.EnumerateFiles(directory, "*.cs", SearchOption.TopDirectoryOnly))
			yield return file;
		foreach (var child in Directory.EnumerateDirectories(directory))
		{
			if (IsExcludedDirectory(Path.GetFileName(child)))
				continue;
			foreach (var file in EnumerateSourceFiles(child))
				yield return file;
		}
	}

	private static bool IsExcludedDirectory(string name) => ExcludedDirectories.Contains(name);

	private static bool IsGeneratedSource(string path) => HasGeneratedSuffix(Path.GetFileName(path)) ||
		File.ReadLines(path).Take(5).Any(line => line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase));

	private static bool HasGeneratedSuffix(string fileName) =>
		GeneratedSuffixes.Any(suffix => fileName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase));

	private static bool ExceedsLimit(int physicalLines) => physicalLines > MaximumPhysicalLines;
}
